const mockTour = {
  id: 126605,
  name:
    "Faster Than Skip-the-Line: Vatican, Sistine Chapel and St. Peter's Basilica Tour",
  path:
    '/tours/faster-than-skip-the-line-vatican-sistine-chapel-and-st-peter-s-basilica-tour',
  overview:
    "Spend more time inside with no-wait access to the Vatican Museums and Sistine Chapel through an official, Vatican partner entrance. On this comprehensive guided tour, you'll experience the best of the Vatican in just three hours, including the Raphael Rooms, St. Peter's, and more. Navigate the vast complex of artwork and history with an expert, who will bring this ancient collection to life. Choose from several departure times, or upgrade to an evening experience or small-group tour with 10 people.",
  description:
    "\u003cb\u003eItinerary\u003c/b\u003e\u003cbr\u003eThis is a typical itinerary for this product\u003cbr\u003e\u003cbr\u003e\u003cb\u003eStop At:\u003c/b\u003e Vatican Museums, Viale Vaticano, 00120 Vatican City Italy\u003cbr\u003e\u003cbr\u003eVatican tours with skip-the-line access are sought-after, so even the fast-track lines are long. This experience includes admission through a special entrance, so there are no lines whatsoever. Follow your guide directly inside the vast collection of private artwork that is the Vatican Museums. \u003cbr\u003e\u003cbr\u003eWalkthrough the Gallery of the Maps and Gallery of Tapestries as you listen to tales of Vatican intrigue. Gaze at artifacts such as timeworn yet fascinating Italian maps, and admire the sculptures and candelabras of the Gallery of Candelabras. Stop for photos in front of the Pigna statue in the Pinecone Courtyard, designed by Dontao Bramante. \u003cbr\u003e\u003cbr\u003e\u003cbr\u003eDuration: 1 hour\u003cbr\u003e\u003cbr\u003e\u003cb\u003eStop At:\u003c/b\u003e Stanze di Raffaello, Viale Vaticano, Vatican City Italy\u003cbr\u003e\u003cbr\u003eRaphael’s Rooms are a series of galleries that highlight the talent of the lauded Renaissance artist himself. \u003cbr\u003e\u003cbr\u003eDuration: 15 minutes\u003cbr\u003e\u003cbr\u003e\u003cb\u003eStop At:\u003c/b\u003e Sistine Chapel, Viale Vaticano, 00165 Vatican City Italy\u003cbr\u003e\u003cbr\u003ePass through the rooms, and then step inside the Sistine Chapel — the pope’s personal place of worship and a highlight of any Vatican trip. Stand beneath Michelangelo’s The Creation of Adam, which cloaks the ceiling, and admire The Last Judgement, his colorful mural that adorns a wall. \u003cbr\u003e\u003cbr\u003eDuration: 20 minutes\u003cbr\u003e\u003cbr\u003e\u003cb\u003eStop At:\u003c/b\u003e St. Peter's Basilica, Piazza San Pietro, 00120 Vatican City Italy\u003cbr\u003e\u003cbr\u003eAfter your Sistine Chapel visit, continue to St Peter’s Basilica, the symbolic heart of the Catholic church. Learn about its history and see more Vatican art including Michelangelo’s La Pietà, which was sculpted when the maestro was only 24 years old. Gaze at the baldachino by Bernini, and then say goodbye to your guide in St Peter’s Square. \u003cbr\u003e\u003cbr\u003eKeep in mind that St Peter's Basilica and St Peter's Square might be unavailable on Wednesdays due to the weekly Papal Audience. As an alternative, you'll be offered an extended itinerary within the Vatican Museums, which still includes the Sistine Chapel and Raphael's Rooms. \u003cbr\u003e\u003cbr\u003eIf you want to make sure that St Peter's Basilica and Square are included in your tour, don't select Wednesday as your travel date. If you want to enhance your Vatican experience, select one of the following experiences: Small-Group Tour at 8:10am: \u003cbr\u003e\u003cbr\u003eEnter the Vatican Museums as soon as it opens, before the other lines enter. \u003cbr\u003e\u003cbr\u003e\u003cbr\u003eDuration: 30 minutes\u003cbr\u003e\u003cbr\u003e\u003cb\u003ePass By:\u003c/b\u003e St. Peter's Square, Piazza San Pietro, 00120 Vatican City Italy\u003cbr\u003e\u003cbr\u003ePassing by\u003cbr\u003e\u003cbr\u003e\u003cb\u003eStop At:\u003c/b\u003e Piazza San Pietro, 00120 Vatican City Italy\u003cbr\u003e\u003cbr\u003eIn just three hours, we’ll introduce you to the artistic treasures of the Vatican City and its main attraction Vatican Museums in an enjoyable and hassle-free manner. From the enormous basilica built over the tomb of St. Peter to Michelangelo's ground-breaking frescoes in the Sistine Chapel, you will see how the Popes used art and culture to spread their message. You’ll leave not just appreciating the Vatican but having understood it too. \u003cbr\u003e\u003cbr\u003eDuration: 3 hours\u003cbr\u003e\u003cbr\u003e",
  price: '57.5605',
  price_currency: 'USD',
  price_type: 'price_per_person',
  min_quantity: 1,
  max_quantity: 15,
  additional_information:
    "Confirmation will be received at time of booking.\u003cbr\u003ePlease bring your own mask on the tour. The wearing of mask is compulsory in order to comply with health \u0026 Safety regulations. Our guide will be wearing mask during the tour as well..\u003cbr\u003eAt the meeting point there will be social distancing taking place. Our guide will organize the group upon your arrival, but we kindly ask yourself to be conscience in taking social distance at all the time from others..\u003cbr\u003eFollowing the new regulations regarding Coronavirus, at the entrance your body temperature will be checked. If a body temperature above 37.5 ° C is registered, you will not be able to enter the site..\u003cbr\u003eNot wheelchair accessible.\u003cbr\u003eNear public transportation.\u003cbr\u003eNo heart problems or other serious medical conditions.\u003cbr\u003eWe regret that we are unable to accommodate guests with wheelchairs or any impairments requiring special assistance. We are also unable to accommodate strollers or baby carriages on our group tours..\u003cbr\u003eGuided visits are not allowed inside St. Peter's on afternoon tours due to religious functions. In this case guides provide full commentary from the Basilica's porch, and guests can visit the interior at their own pace without the guide.\u003cbr\u003eTours departing Wednesday: There is a possibility that St Peter's Basilica and St Peter's Square will be unavailable due to the weekly Papal Audience during which access to St Peter's Basilica is closed..\u003cbr\u003eAvoid bringing large purses, bags, or backpacks on your tour.\u003cbr\u003eTravelers should have a moderate physical fitness level.\u003cbr\u003eWe may experience delays in getting through mandatory security checks when entering these venues.\u003cbr\u003eThis experience requires a minimum number of travelers. If it’s canceled because the minimum isn’t met, you’ll be offered a different date/experience or a full refund.\u003cbr\u003eThis tour/activity will have a maximum of 20 travelers.\u003cbr\u003eFace masks required for travelers in public areas.\u003cbr\u003eFace masks required for guides in public areas.\u003cbr\u003eSocial distancing enforced throughout experience.\u003cbr\u003eTemperature checks for travelers upon arrival.\u003cbr\u003eOur group size is 10 people or less complying with the venue regulations during this post-Covid-19.",
  inclusion:
    "Professional guide.\u003cbr\u003eHeadsets to hear the guide clearly (when group size is 20 people).\u003cbr\u003ePriority Access to the Vatican.\u003cbr\u003eEntry/Admission - Vatican Museums.\u003cbr\u003eEntry/Admission - Stanze di Raffaello.\u003cbr\u003eEntry/Admission - Sistine Chapel.\u003cbr\u003eEntry/Admission - St. Peter's Basilica",
  exclusion:
    "Gratuities.\u003cbr\u003eHotel pickup and drop-off.\u003cbr\u003eFood and drinks.\u003cbr\u003eSt. Peter's Basilica is not included until further notice",
  starting_time: null,
  duration_in_minutes: 150,
  duration_in_text: '2 hours 30 minutes',
  languages: ['English - Guide'],
  meeting_point_or_pickup_address:
    'Via Tunisi, 4, 00192 Roma RM, Italy\u003cbr /\u003e',
  privacy_type: 'public_tour',
  images: [
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/bcfa49cb-e3c8-4416-8ccc-077b760b690b/a2110665-10b1-434d-98f6-4a0634b337dd.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/5ec2533c-4c10-4121-aa75-330dc5b666e5/61315923-4716-430b-afdf-5313d7c649cd.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/b45e16b8-a331-45a6-8766-8b86f631d1fc/fccf3f4d-c068-4bec-8805-ab592721cfcf.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/21936bae-b922-447e-80c3-d7345a27ecef/5198e932-fd88-4b14-bc36-4ce01a9b5f35.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/45972fe5-428c-47ba-b01a-511d409f45a5/58b5615f-f696-4b00-8764-f2c7be06f1ba.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/a84694e8-9714-4bbc-a499-377f0dab6590/179aeefb-0666-471c-90fa-52b0b214e815.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/21a642b9-8809-4c01-8be0-ec106ce38a76/24010dc9-8883-4b67-bc0b-b18284df72f0.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/5d09f61a-9426-4ea0-a664-54961e9e2dbe/580cc7bc-b595-4801-9516-68385cea8637.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/949cd1a8-21b2-45e4-b059-f35cde0e7628/6dfdd9d8-2519-4dcb-9fa6-529c73243e3b.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/64fc3947-8960-4f02-b840-2a12ba687b89/8fed7ae9-dc85-49b1-9293-98de29790484.jpg',
    'https://d1qq4h2hdonqwg.cloudfront.net/uploads/tour_image/file/1f146f22-04b5-4772-aa96-e653ccf86519/94810e6b-9c7d-40a3-8d6d-8a74253d205b.jpg',
  ],
  categories: [
    'Cultural Tours',
    'Historical \u0026 Heritage Tours',
    'Walking Tours',
  ],
  instant_confirmation: true,
  cancellation_policy:
    'For a full refund, cancel at least 24 hours in advance of the start date of the experience',
  age_bands: [
    {
      sortOrder: 1,
      ageFrom: 19,
      ageTo: 99,
      adult: true,
      bandId: 1,
      pluralDescription: 'Adults',
      treatAsAdult: true,
      count: 0,
      description: 'Adult',
    },
    {
      sortOrder: 2,
      ageFrom: 6,
      ageTo: 18,
      adult: false,
      bandId: 2,
      pluralDescription: 'Children',
      treatAsAdult: false,
      count: 0,
      description: 'Child',
    },
    {
      sortOrder: 3,
      ageFrom: 0,
      ageTo: 5,
      adult: false,
      bandId: 3,
      pluralDescription: 'Infants',
      treatAsAdult: false,
      count: 0,
      description: 'Infant',
    },
  ],
  booking_questions: [],
  hotel_pickup: false,
  booking_flow_type: 1,
  locations: [
    {
      id: 1510,
      name: 'Rome',
      latitude: '41.902784',
      longitude: '12.496366',
      google_place_id: 'ChIJZcOWEKZhLxMR2f10GClhgJ4',
      slug: null,
      created_at: '2016-09-23T13:36:52.644-05:00',
      updated_at: '2017-10-10T22:57:53.281-05:00',
      city_id: 69,
      country_id: 108,
      street_number: null,
      route: null,
      locality: null,
      administrative_area_level_1: null,
      country: null,
      postal_code: null,
      address: null,
      thumb_url: null,
      is_attraction: false,
      location_type: 'normal',
    },
    {
      id: 102719,
      name: 'Vatican',
      latitude: '41.905815',
      longitude: '12.454587',
      google_place_id: null,
      slug: 'viale-vaticano',
      created_at: '2019-07-16T19:16:20.656-05:00',
      updated_at: '2019-12-02T13:11:33.892-06:00',
      city_id: 69,
      country_id: 108,
      street_number: null,
      route: null,
      locality: 'Rome',
      administrative_area_level_1: null,
      country: null,
      postal_code: null,
      address: 'Viale Vaticano',
      thumb_url:
        'http://cache-graphicslib.viator.com/graphicslib/page-images/742x525/321867_Viator_Photographer_124125.jpg',
      is_attraction: true,
      location_type: 'attraction',
    },
    {
      id: 102722,
      name: 'Sistine Chapel',
      latitude: '41.902946',
      longitude: '12.454484',
      google_place_id: null,
      slug: 'st-peter-s-square',
      created_at: '2019-07-16T19:17:29.209-05:00',
      updated_at: '2019-12-02T13:15:30.368-06:00',
      city_id: 69,
      country_id: 108,
      street_number: null,
      route: null,
      locality: 'Rome',
      administrative_area_level_1: null,
      country: null,
      postal_code: null,
      address: 'St Peter’s Square',
      thumb_url:
        'http://cache-graphicslib.viator.com/graphicslib/page-images/742x525/311703_Viator_User_Generated_43953.jpg',
      is_attraction: true,
      location_type: 'attraction',
    },
    {
      id: 102724,
      name: "St Peter's Basilica",
      latitude: '41.90219',
      longitude: '12.454782',
      google_place_id: null,
      slug: 'piazza-san-pietro-48865c6b-88ed-46d2-9eff-61961f7d1e83',
      created_at: '2019-07-16T19:17:53.095-05:00',
      updated_at: '2019-12-02T13:16:59.348-06:00',
      city_id: 69,
      country_id: 108,
      street_number: null,
      route: null,
      locality: 'Rome',
      administrative_area_level_1: null,
      country: null,
      postal_code: null,
      address: 'Piazza San Pietro',
      thumb_url:
        'http://cache-graphicslib.viator.com/graphicslib/page-images/742x525/300559_Viator_Shutterstock_167340.jpg',
      is_attraction: true,
      location_type: 'attraction',
    },
    {
      id: 102734,
      name: "St. Peter's Square",
      latitude: '41.902237',
      longitude: '12.457256',
      google_place_id: null,
      slug: 'piazza-san-pietro-354f61d6-89ba-41f2-ad64-79f297a53634',
      created_at: '2019-07-16T19:18:30.729-05:00',
      updated_at: '2019-12-02T13:19:33.928-06:00',
      city_id: 69,
      country_id: 108,
      street_number: null,
      route: null,
      locality: 'Rome',
      administrative_area_level_1: null,
      country: null,
      postal_code: null,
      address: 'Piazza san Pietro',
      thumb_url:
        'http://cache-graphicslib.viator.com/graphicslib/page-images/742x525/143136_Rome_St%20Peter%20Square_shutterstock_111647705.jpg',
      is_attraction: true,
      location_type: 'attraction',
    },
    {
      id: 102737,
      name: "Raphael's Rooms",
      latitude: '41.905618',
      longitude: '12.45784',
      google_place_id: null,
      slug: 'viale-vaticano-d72a3f56-2fcb-499a-b3da-9795fbae0237',
      created_at: '2019-07-16T19:18:56.674-05:00',
      updated_at: '2019-12-02T13:21:46.071-06:00',
      city_id: 69,
      country_id: 108,
      street_number: null,
      route: null,
      locality: 'Rome',
      administrative_area_level_1: null,
      country: null,
      postal_code: null,
      address: 'Viale Vaticano',
      thumb_url:
        'http://cache-graphicslib.viator.com/graphicslib/page-images/742x525/114602_raphaelvat_shutterstock_51885448.jpg',
      is_attraction: true,
      location_type: 'attraction',
    },
  ],
  average_rating: 5.0,
  no_of_reviews: 146,
  favorites_count: 0,
  favorited: false,
  reviews: [
    {
      id: 1387036,
      title: null,
      comment:
        '\u003cp\u003eawesome experience the tour guide was very knowledgeable and passionate and the tour was amazing..  Well worth doing no queuing great value\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-10-19T00:00:00.000-05:00',
      reviewer_name: 'paul',
      reviewer_avatar: null,
    },
    {
      id: 1387037,
      title: null,
      comment:
        '\u003cp\u003eAn Incredible experience!  Our guide Lindee was very knowledgeable and extremely friendly, answered any questions we had with ease.  The guided tour really helped us understand our surroundings and historic architecture. I would wholeheartedly recommend this trip, the Vatican museum was like no other I have seen so many Treasures, the Sistine Chapel was truly amazing.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-10-05T00:00:00.000-05:00',
      reviewer_name: 'Bridgette K',
      reviewer_avatar: null,
    },
    {
      id: 1387038,
      title: null,
      comment:
        '\u003cp\u003eSylvia was an amazing tour guide, full of knowledge and constantly interacting with all of us. Sylvia gets a full 10 stars from us, thank you. Highly recommend \u003cbr/\u003e\nAlison  and  Steve from Manchester\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-09-30T00:00:00.000-05:00',
      reviewer_name: 'Alison',
      reviewer_avatar: null,
    },
    {
      id: 1387040,
      title: null,
      comment:
        '\u003cp\u003eDid small group tour with Salvatore. The Vatican is breath-taking and awe inspiring. No place on Earth like it. Salvatore extremely well organised .Appreciated him sharing his passion for such a wonderful place and the geniuses who built and decorated it. Grazie.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-09-10T00:00:00.000-05:00',
      reviewer_name: 'a.j.key',
      reviewer_avatar: null,
    },
    {
      id: 1387039,
      title: null,
      comment:
        '\u003cp\u003eSal was fantastic, really lovely and explained everything perfectly. Really enjoyed the tour and would definitely book again.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-09-10T00:00:00.000-05:00',
      reviewer_name: 'Adele',
      reviewer_avatar: null,
    },
    {
      id: 1387041,
      title: null,
      comment:
        '\u003cp\u003eFabulous tour and very informative guide!\u003cbr/\u003e\nVery safe during Covid, masks, temperature taken.\u003cbr/\u003e\nWould recommend this tour!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-09-07T00:00:00.000-05:00',
      reviewer_name: 'Marion B',
      reviewer_avatar: null,
    },
    {
      id: 1387046,
      title: null,
      comment:
        '\u003cp\u003eGigi was fantastic! We could feel his passion for the Vatican and it made our group so excited to learn about everything - we can definitely recommend this to anyone!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-08-13T00:00:00.000-05:00',
      reviewer_name: 'Alain C',
      reviewer_avatar: null,
    },
    {
      id: 1387043,
      title: null,
      comment:
        '\u003cp\u003eOur guide Alessandra, was fantastic and  so passionate about the place , We learnt so much from her , things that would have passed us by , her knowledge was astounding\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-08-13T00:00:00.000-05:00',
      reviewer_name: 'Lucinda D',
      reviewer_avatar: null,
    },
    {
      id: 1387047,
      title: null,
      comment:
        '\u003cp\u003eOur guide was a wealth of information and extremely knowledgeable which helped us enjoy the tour thoroughly.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-07-31T00:00:00.000-05:00',
      reviewer_name: 'Matthew D',
      reviewer_avatar: null,
    },
    {
      id: 1387049,
      title: null,
      comment:
        '\u003cp\u003eVery nice visit to the Vatican with a good guide. I can recommed this tour of the Vatican. It was a good experience\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-07-27T00:00:00.000-05:00',
      reviewer_name: 'Kristofer M',
      reviewer_avatar: null,
    },
    {
      id: 1387051,
      title: null,
      comment:
        '\u003cp\u003eOur guide was well versed and very professional. She answered all our questions and even gave us information not included elsewhere.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-07-16T00:00:00.000-05:00',
      reviewer_name: 'Donald',
      reviewer_avatar: null,
    },
    {
      id: 1387053,
      title: null,
      comment:
        "\u003cp\u003eThe tour was pretty much perfect in every kind of way. The meeting point was easy to navigate and find, and the staff were very professional on arrival. Our guide was friendly, clear and had a lot of knowledge which she shared with the group very well. \u003c/p\u003e\n\n\u003cp\u003eThe Vatican museums are absolutely huge, and I feel that without a tour, you would end up needing an entire day to have a look round. The tour was good in this sense as it focused on the highlights, but didn't feel too rushed at any point. If you are someone who wants to really take their time in the museums, and look around at everything, a tour isn't for you. The tour lasted 3 hours and concluded in St Peter's Basilica, where you will have a quick tour and then be allowed to free roam. It's possible to visit St Peter's square very easily after the tour finishes. \u003c/p\u003e\n\n\u003cp\u003eMy only slight complaint is that they should invest in better headsets. If you were too far away from the guide, it would either become very muffled or cut off entirely.\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-04-06T00:00:00.000-05:00',
      reviewer_name: 'smalik997',
      reviewer_avatar: null,
    },
    {
      id: 1387055,
      title: null,
      comment:
        "\u003cp\u003eExcellent guide and very informative tour of The Vatican.  I'm not a big fan of organised religion but it's fascinating to see the wealth the Catholic church has amassed over the centuries and how Sheeple continue to blindly follow despite the scandals and corruption.\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-03-09T00:00:00.000-05:00',
      reviewer_name: 'xdamientt',
      reviewer_avatar: null,
    },
    {
      id: 1387060,
      title: null,
      comment:
        '\u003cp\u003eFabulous guide...so knowledgeable. Made it an exciting and informative visit. Would definitely recommend it. Well done!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-03-05T00:00:00.000-06:00',
      reviewer_name: 'Yve.Field',
      reviewer_avatar: null,
    },
    {
      id: 1387057,
      title: null,
      comment:
        "\u003cp\u003ePartner and I visited in late February and our tour guide was Lorena. She's an archaeologist and super passionate about everything she taught us - the buildings, history, the artists. Everything was so gorgeous but the only issue is that the Vatican and Raphael's Rooms are packed to the brim with hundreds of people and everyone is being herded through. You can't really stop to examine (and art is everywhere, floor and walls and ceilings). That part was frustrating but not Lorena's fault at all ofc. I would recommend doing this tour and learning a lot in 3 hours and then coming back on your own one day to walk through everywhere slowly.\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-03-05T00:00:00.000-06:00',
      reviewer_name: 'Ayesha Umme-Jihad',
      reviewer_avatar: null,
    },
    {
      id: 1387062,
      title: null,
      comment:
        '\u003cp\u003eThe tour was worth every single penny. Very informative. And our guide was very knowledgeable, friendly and her English was excellent. I don’t think we would have learnt as much self guided so I recommend a tour every time. You hear so many more stories and extra details with a tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-03-04T00:00:00.000-06:00',
      reviewer_name: 'AMY D',
      reviewer_avatar: null,
    },
    {
      id: 584776,
      title: null,
      comment:
        '\u003cp\u003eThe guide was great and very informative. The trip was enjoyable with time given to rest, use restroom or grab a snack! Great experience\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-26T00:00:00.000-06:00',
      reviewer_name: 'Earl K',
      reviewer_avatar: null,
    },
    {
      id: 584775,
      title: null,
      comment:
        '\u003cp\u003eVery knowledgeable and friendly guide who coordinated everything.  Would highly recommend this tour company.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-26T00:00:00.000-06:00',
      reviewer_name: 'Matthew B',
      reviewer_avatar: null,
    },
    {
      id: 584774,
      title: null,
      comment:
        '\u003cp\u003eSuper informed guide who had a lovely manner and very attentive to questions. Thoroughly enjoy the morning.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-26T00:00:00.000-06:00',
      reviewer_name: 'ANTHONY L',
      reviewer_avatar: null,
    },
    {
      id: 584777,
      title: null,
      comment:
        "\u003cp\u003eTour was professionally organize.  Our guide Francesca O. was energetic, well informed and down to earth.  Just enough tutorial to learn but to keep the experience genuine. Felt group was perfect size on the Semi-private tour.  Pace was good, very thankful to have   additional time thru Sistine Chapel and inside Saint Peter's Basilica.  Thank you, Jorge\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-25T00:00:00.000-06:00',
      reviewer_name: 'Jorge R',
      reviewer_avatar: null,
    },
    {
      id: 584779,
      title: null,
      comment:
        '\u003cp\u003eFast track and no waiting... stunning paintings in Sistine Chapel and magnificent St Peter’s Basilica...a must when in Rome.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-24T00:00:00.000-06:00',
      reviewer_name: 'Min S',
      reviewer_avatar: null,
    },
    {
      id: 584778,
      title: null,
      comment:
        '\u003cp\u003eExcellent tour guide in a smallish group of 20. Very knowledgable and friendly. Meeting point was easy to find too.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-24T00:00:00.000-06:00',
      reviewer_name: 'Iain G',
      reviewer_avatar:
        'http://cache-graphicslib.viator.com/graphicslib/media/76/iain-g-account_9266550-45sq.jpg',
    },
    {
      id: 584782,
      title: null,
      comment:
        '\u003cp\u003eGuide was very knowledgeable about the Vatican history and willing to answer all our questions.    Super pleasant!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-20T00:00:00.000-06:00',
      reviewer_name: 'Eudaldo G',
      reviewer_avatar: null,
    },
    {
      id: 584781,
      title: null,
      comment:
        '\u003cp\u003eIncredible tour, our guide Palou was so interesting and helpful. She was very enthusiastic about her work.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-20T00:00:00.000-06:00',
      reviewer_name: 'Geraldine O',
      reviewer_avatar:
        'http://cache-graphicslib.viator.com/graphicslib/media/a4/geraldine-o-account_32708772-45sq.jpg',
    },
    {
      id: 584780,
      title: null,
      comment:
        '\u003cp\u003eExcellent tour in 3 hours. Main things covered. Great guide with a fountain of knowledge. Felt very safe and in good hands.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-20T00:00:00.000-06:00',
      reviewer_name: 'Grant R',
      reviewer_avatar: null,
    },
    {
      id: 584788,
      title: null,
      comment:
        "\u003cp\u003eOur guide, Renatta, was very knowledgeable about the Vatican, Sistine Chapel and St Peter's Basilica.  She provided significant details about the many amazing works of art and history  which made the tour one of the highlights of our trip to Rome.  We booked our tickets online and found the directions of where to meet easy to find.  I would highly recommend booking a tour with this company.\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-19T00:00:00.000-06:00',
      reviewer_name: 'Lance V',
      reviewer_avatar: null,
    },
    {
      id: 584787,
      title: null,
      comment:
        '\u003cp\u003eMyself and my partner visited the Vatican City for valentines weekend. Our guide was great, she gave a very detailed explanation whilst walking round the Vatican. Tour lasted 2hrs 30mins which is a good time. Well organised.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-19T00:00:00.000-06:00',
      reviewer_name: 'steve-wright13',
      reviewer_avatar: null,
    },
    {
      id: 584786,
      title: null,
      comment:
        '\u003cp\u003eThe tour was quite a fine experience.  Francesca was gave us an ongoing rich understanding of the art we were seeing and of the people behind the art.  She was excellent.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-19T00:00:00.000-06:00',
      reviewer_name: 'Michael A',
      reviewer_avatar: null,
    },
    {
      id: 584785,
      title: null,
      comment:
        '\u003cp\u003eVery good instructions how to get to meeting point. 21 in our group and Marcus our guide was funny as well as obviously very well informed about the history of the Vatican City. \u003cbr/\u003e\nWe were not rushed and had time to look listen and digest.  Marcus was funny and answered all questions. Highly recommend this tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-19T00:00:00.000-06:00',
      reviewer_name: 'Barbara W',
      reviewer_avatar: null,
    },
    {
      id: 584784,
      title: null,
      comment:
        "\u003cp\u003eThis tour was fantastic. First you avoid the hundreds of people waiting. Second the tour guide Sarah was very informative, friendly and professional. Then the tour itself of the Vatican Museum, Sistine Chapel and St. Peter's is a once in a lifetime experience!\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-19T00:00:00.000-06:00',
      reviewer_name: 'TB FiglioBD',
      reviewer_avatar: null,
    },
    {
      id: 584783,
      title: null,
      comment:
        '\u003cp\u003eOur guide Laura was great and knew everything about the Vatican. She made the experience very enjoyable.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-19T00:00:00.000-06:00',
      reviewer_name: 'Peter A',
      reviewer_avatar: null,
    },
    {
      id: 584792,
      title: null,
      comment:
        '\u003cp\u003eExcellent tour. Sara was an outstanding guide - knowledgeable and very pleasant. Would recommend to anyone wanting to visit the Vatican.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-17T00:00:00.000-06:00',
      reviewer_name: 'Michael L',
      reviewer_avatar: null,
    },
    {
      id: 584791,
      title: null,
      comment:
        '\u003cp\u003eMy husband and I recently attended this tour and had a knowledgeable and friendly tour guide, Fabio. We were able to get in quickly without waiting online and visited the Vatican, sistene chapel and saint peters. This was a great tour for which I highly recommend!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-17T00:00:00.000-06:00',
      reviewer_name: 'Brittany E',
      reviewer_avatar: null,
    },
    {
      id: 584790,
      title: null,
      comment:
        '\u003cp\u003eThe tour was amazing, the tour guide was superb - providing excellent and interesting facts. Can only recommend this tour\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-17T00:00:00.000-06:00',
      reviewer_name: 'Irina E',
      reviewer_avatar: null,
    },
    {
      id: 584789,
      title: null,
      comment:
        '\u003cp\u003eThe guide knew his history well and you could tell he was proud of the city. Very informative and skip the line was great as I only had the day in Rome.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-17T00:00:00.000-06:00',
      reviewer_name: 'Stuart P',
      reviewer_avatar: null,
    },
    {
      id: 584793,
      title: null,
      comment:
        '\u003cp\u003eThis was well worth the money to skip two enormous lines. Our tour guide Oscar was very knowledgable. Great experience.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2020-02-12T00:00:00.000-06:00',
      reviewer_name: 'Cathy C',
      reviewer_avatar: null,
    },
    {
      id: 519228,
      title: null,
      comment:
        '\u003cp\u003eWe are a family of 2 adults and 2 teens.  Booked this tour upon recommendation from a friend.  So glad we did.  So worth it to 1. Skip the line 2.  Great having a small group to maneuver through the crowds at the Vatican 3.  Very knowledgeable guide, learned a lot and we made the most out of our time at the Vatican.  The tour ends after the St Peter’s Basilica portion but before exiting  so you have time to go to top of dome and/or under Basilica on your own if you want to.  Highly recommend!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-08T00:00:00.000-05:00',
      reviewer_name: 'Tami L',
      reviewer_avatar: null,
    },
    {
      id: 519232,
      title: null,
      comment:
        "\u003cp\u003eGuide was informative and funny.  Hit all highlights in 3 hours and did not have to wait..... This is a must for Vatican, Sistine Chapel and St Peter's Basilica visitors.   Great value for the money.....\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-05T00:00:00.000-05:00',
      reviewer_name: 'Eric B',
      reviewer_avatar: null,
    },
    {
      id: 519231,
      title: null,
      comment:
        '\u003cp\u003eTour guide Pavlo is amazing, energetic and passionate in explanations and story telling. The heat was unbearable but she tried to find shades to make us as comfortable as possible. Very good .\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-05T00:00:00.000-05:00',
      reviewer_name: 'Ron L',
      reviewer_avatar: null,
    },
    {
      id: 519230,
      title: null,
      comment:
        '\u003cp\u003eOur experience on this tour was fantastic. Our guide was very knowledgeable and through. Life changing experience!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-05T00:00:00.000-05:00',
      reviewer_name: 'theparviainens',
      reviewer_avatar: null,
    },
    {
      id: 519229,
      title: null,
      comment:
        '\u003cp\u003eFrancesca O. was a wonderful tour guide, and though there was a lot of ground to cover on a very hot day, she was enthusiastic and very informative.  We enjoyed the tour very much!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-05T00:00:00.000-05:00',
      reviewer_name: 'Michelle T',
      reviewer_avatar: null,
    },
    {
      id: 519237,
      title: null,
      comment:
        '\u003cp\u003eThis was our second experience with a Tour booked with Viator.  The other one was in Pompeii.  In both cases, the experience was fantastic.  It was very easy to contact our guide at the start of the tour and the entrance to the Vatican went very smooth, even though the general access was very crowded.\u003c/p\u003e\n\n\u003cp\u003eI went with my wife and my 11 year old daughter and the guides were specially kind and attentive with my kid,\u003c/p\u003e\n\n\u003cp\u003eFinally, our guide was full of interesting information about the sites and delivered in a relaxed and engaging way.\u003c/p\u003e\n\n\u003cp\u003eI absolutely recommend this tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-02T00:00:00.000-05:00',
      reviewer_name: 'Gian P',
      reviewer_avatar: null,
    },
    {
      id: 519236,
      title: null,
      comment:
        '\u003cp\u003eOscar was a fantastic tour guide. He was very charismatic and informative, not once did he lose my interest. 10/10 would recommend!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-02T00:00:00.000-05:00',
      reviewer_name: 'Mario S',
      reviewer_avatar: null,
    },
    {
      id: 519235,
      title: null,
      comment:
        '\u003cp\u003eOur guide was terrific.  So knowledgeable.  Being able to walk right in and not have to wait in any of the lines was a HUGE perk. Highly recommend this tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-02T00:00:00.000-05:00',
      reviewer_name: 'Bonnie W',
      reviewer_avatar: null,
    },
    {
      id: 519234,
      title: null,
      comment:
        '\u003cp\u003eThis is NOT an easy tour for a guide as the Vatican was packed but our guide was fabulous. She was super informative, totally charming, knew how to get us through the rooms, funny, wonderful for the variety of ages of our group and just a wonderful guide. High recommend this experience!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-02T00:00:00.000-05:00',
      reviewer_name: 'Victoria P',
      reviewer_avatar: null,
    },
    {
      id: 519233,
      title: null,
      comment:
        '\u003cp\u003eI had a wonderful visit to the Vatican with Paola of Citywonders. We were met at the exact location as indicated and check in was quick. Our tour guide Paola spoke excellent English, had a great sense of humour and was very knowledgeable about the Basilica, the Sistene Chapel and the Vatican in general. I had a great time!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-02T00:00:00.000-05:00',
      reviewer_name: 'lisa_falconi',
      reviewer_avatar: null,
    },
    {
      id: 519238,
      title: null,
      comment:
        '\u003cp\u003eGreat tour guide wonderful experience, so glad we took this tour,. would definitely recomend to any one\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-08-01T00:00:00.000-05:00',
      reviewer_name: 'Valerie C',
      reviewer_avatar: null,
    },
    {
      id: 519241,
      title: null,
      comment:
        '\u003cp\u003eAlessandra was my guide and she was one of a kind excellent. This tour is a must as the Vatican is so vast and this takes you where you want to go. She provided memorable insight I will take with me! Worth the price 100%.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-31T00:00:00.000-05:00',
      reviewer_name: 'Kristi S',
      reviewer_avatar: null,
    },
    {
      id: 519240,
      title: null,
      comment:
        '\u003cp\u003eThis tour was simply amazing!  Martina was so knowledgeable, friendly, and professional.  The members of our family ranged in age from 6 to 70 and Martina made sure everyone was okay.  I have been to the Vatican before, but never did I learn as much as I did on this tour!!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-31T00:00:00.000-05:00',
      reviewer_name: 'kmancini3',
      reviewer_avatar: null,
    },
    {
      id: 519239,
      title: null,
      comment:
        '\u003cp\u003eHighly recommend Francesca O. Her knowledge about the Vatican museums, the Basilica and the Sistine Chapel were impressive.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-31T00:00:00.000-05:00',
      reviewer_name: 'vieques07836',
      reviewer_avatar: null,
    },
    {
      id: 519243,
      title: null,
      comment:
        '\u003cp\u003eGreat tour and great tour guide. The meet place was very easy and lots of staff to help you find your group.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-30T00:00:00.000-05:00',
      reviewer_name: 'susanbartush',
      reviewer_avatar: null,
    },
    {
      id: 519242,
      title: null,
      comment:
        '\u003cp\u003eFantastic tour a must see with a fantastic tour guide. Our guide Titiana was enthusiastic and knowledgeable and it was a pleasure to be shown around these wonderful attractions by her. Best tour guide by far that we encountered in our 14 days abroad.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-30T00:00:00.000-05:00',
      reviewer_name: 'xr6t4gc',
      reviewer_avatar: null,
    },
    {
      id: 519251,
      title: null,
      comment:
        '\u003cp\u003eOur family toured Vatican City with Big Mama G. She was friendly and approachable and so knowledgeable about everything we saw. When we came across a young boy who’d lost his mother, she took him under her wing and made sure he was well taken care of. \u003cbr/\u003e\nIf you’re planning a tour in Rome, ask for Big Mama G! She really is the best! ????\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-29T00:00:00.000-05:00',
      reviewer_name: 'Grant S',
      reviewer_avatar: null,
    },
    {
      id: 519250,
      title: null,
      comment:
        '\u003cp\u003eim speechless fantastic amazing eye opening \u003cbr/\u003e\njust do it its a once in a lifetime experience everyone should experience and see the art!!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-29T00:00:00.000-05:00',
      reviewer_name: 'simonmakdesian',
      reviewer_avatar: null,
    },
    {
      id: 519249,
      title: null,
      comment:
        '\u003cp\u003eOur tour was on July 26th at noon. It was very easy to find city tour reps outside the Vatican. Our tour guide was brilliant. Very knowledgable, witty and kept us all together in such large crowds. Would definitely recommend this tour to others\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-29T00:00:00.000-05:00',
      reviewer_name: 'reillytony2010',
      reviewer_avatar: null,
    },
    {
      id: 519248,
      title: null,
      comment:
        '\u003cp\u003eAlisa our guide was great! Provided good information but kept our group moving  and engaged as it was a packed day.  Our kids 15, 12 and 11 were engaged. Thank you!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-29T00:00:00.000-05:00',
      reviewer_name: 'Tania B',
      reviewer_avatar: null,
    },
    {
      id: 519247,
      title: null,
      comment:
        '\u003cp\u003eOur guide was excellent. It’s really unfortunate that I forgot her name because she deserves to be mention.\u003cbr/\u003e\nShe tools us through the map museum and explained everything so well. The basilica is breathtaking and of course the high light of the tour! The Sistine chapel. No words! I was absolutely overwhelmed with emotions. To think that we were standing and looking at this work of art painted by Michelangelo.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-29T00:00:00.000-05:00',
      reviewer_name: 'Cristina C',
      reviewer_avatar: null,
    },
    {
      id: 519246,
      title: null,
      comment:
        '\u003cp\u003eOur guide, Sara N. Was exceptional. She went above and beyond and knew the ins and outs about each artwork, sculpture and historical artifact. Definately recommend to others to attend this tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-29T00:00:00.000-05:00',
      reviewer_name: 'Hiten P',
      reviewer_avatar:
        'http://cache-graphicslib.viator.com/graphicslib/media/19/hiten-p-account_20949017-45sq.jpg',
    },
    {
      id: 519245,
      title: null,
      comment:
        '\u003cp\u003eGreat tour led by excellent tour guide. Obviously it was very crowded but it went very smoothly. Thanks\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-29T00:00:00.000-05:00',
      reviewer_name: 'Madhukar L',
      reviewer_avatar: null,
    },
    {
      id: 519244,
      title: null,
      comment:
        '\u003cp\u003eThis tour was better than I could have thought. Tour leader was comprehensive and incredibly knowledgeable. Would recommend to everyone.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-07-29T00:00:00.000-05:00',
      reviewer_name: 'David K',
      reviewer_avatar: null,
    },
    {
      id: 496087,
      title: null,
      comment:
        '\u003cp\u003eWhile in Rome me and my wife thought it we would take the obligatory trip to the Vatican. Our guide Christian made the experience much more than we could have ever hoped. His excitement and passion when explaining the history and artwork behind every corner made for a memorable experience and I would recommend the trip for anyone.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-13T00:00:00.000-05:00',
      reviewer_name: 'Nikolos M',
      reviewer_avatar: null,
    },
    {
      id: 496086,
      title: null,
      comment:
        '\u003cp\u003eMela was our guide and she was fantastic! We arrived at the steps described in the directions and there were many people there to greet and help us. The tour lasted over three hours and our guide was very knowledgeable and helpful. The sites were beautiful and breathtaking. A must-see and I highly recommend that you do a skip the line tour because it is overwhelmingly crowded there.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-13T00:00:00.000-05:00',
      reviewer_name: 'Marilyn G',
      reviewer_avatar: null,
    },
    {
      id: 496085,
      title: null,
      comment:
        '\u003cp\u003eWe had an amazing time even though the crowds of people were out of control.  I wish they would limit the amount of people that tour through the day (25,000).  You could not really get a clear understanding of everything that was explained because of the amount of people.  Our guide was terrific.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-13T00:00:00.000-05:00',
      reviewer_name: 'lamb414',
      reviewer_avatar: null,
    },
    {
      id: 496084,
      title: null,
      comment:
        '\u003cp\u003eSmall group of 20 was very manageable and the audio headsets were a great help. Crowds were large in the Raphael rooms but our guide Alessandra, gave us the option to visit or not. She took extra time with us and was a fun, energetic person. We loved it!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-13T00:00:00.000-05:00',
      reviewer_name: 'lynneeverest9',
      reviewer_avatar: null,
    },
    {
      id: 496083,
      title: null,
      comment:
        '\u003cp\u003eLoved our tour, Livia was so knowledgeable and nice. Glad we got her for our guide! The Sistine chapel and the Vatican have such rich history.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-13T00:00:00.000-05:00',
      reviewer_name: 'Jayne H',
      reviewer_avatar: null,
    },
    {
      id: 496082,
      title: null,
      comment:
        "\u003cp\u003eIn my opinion this is a must see if you're in Rome.  Our guide was excellent and full of information.\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-13T00:00:00.000-05:00',
      reviewer_name: 'Henry',
      reviewer_avatar: null,
    },
    {
      id: 496090,
      title: null,
      comment:
        '\u003cp\u003ePaulo was an excellent tour guide and we thoroughly enjoyed our time.  He was patient with our group as we travelled with young children and was happy to give excellent detail about the magnificent works of art.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-09T00:00:00.000-05:00',
      reviewer_name: 'Amanda G',
      reviewer_avatar: null,
    },
    {
      id: 496089,
      title: null,
      comment:
        '\u003cp\u003eThis was a first time visit to Rome and the Vatican. Our tour guide showed us so many things hat we would have missed had we toured on our own. She gave us historical, artistic and spiritual viewpoints as we proceeded through the tour. Her own perspective of a Rome native sharing her love of the city and culture enhanced our experience.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-09T00:00:00.000-05:00',
      reviewer_name: 'Lois C',
      reviewer_avatar: null,
    },
    {
      id: 496088,
      title: null,
      comment:
        '\u003cp\u003eOur guide, Eduardo, was excellent, knowledgeable and fun.  The tour was just beautiful.  Wouldn’t have done it any other way.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-09T00:00:00.000-05:00',
      reviewer_name: 'Venus B',
      reviewer_avatar: null,
    },
    {
      id: 496092,
      title: null,
      comment:
        '\u003cp\u003eWe took the Vatican and Basilica tour with Chad as our excellent guide. His knowledge and explanations were fantastic and made the tour all the more enjoyable. We would highly recommend 5*****\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-08T00:00:00.000-05:00',
      reviewer_name: 'Carolyn M',
      reviewer_avatar: null,
    },
    {
      id: 496091,
      title: null,
      comment:
        "\u003cp\u003eOur guide was knowledgeable. Very interesting, fascinating. Was wonderful to be in the Sistine Chapel and St. Peter's Basilica!\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-08T00:00:00.000-05:00',
      reviewer_name: 'Judy P',
      reviewer_avatar: null,
    },
    {
      id: 496093,
      title: null,
      comment:
        '\u003cp\u003eWith less than 24 hours in Rome, we had to be sure that our time was optimized. The meetup point was easy to reach from the closest train station (used Google Maps app) and the guides were quick and organized. We were shuffled into a group and took off within 15 minutes, skipping the incredibly long line that wrapped against the outer wall. Our guide Gigi was charismatic and informative, making sure that we had enough time to appreciate all the wonders while moving forward at a good pace. Despite there being a tremendous amount to take in, we were able to finish under three hours with the remainder of the time up to us to utilize as we pleased. Great experience!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-07T00:00:00.000-05:00',
      reviewer_name: 'Becky L',
      reviewer_avatar: null,
    },
    {
      id: 496098,
      title: null,
      comment:
        '\u003cp\u003eMy husband and I thoroughly enjoyed our tour of the Vatican museum, Sistine Chapel,  and  St. Paul’s Cathedral. Our guide Barbara was lovely and knowledgeable throughout the entire tour! She kept us engaged the entire time! definitely recommend City Wonders! Thanks again for the tour, Barbara! :)\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-06T00:00:00.000-05:00',
      reviewer_name: 'Amy L',
      reviewer_avatar: null,
    },
    {
      id: 496097,
      title: null,
      comment:
        '\u003cp\u003eThere is no other way to tour the Vatican than on a planned tour with a knowledgeable guide. Our experience was wonderful and we highly recommend this tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-06T00:00:00.000-05:00',
      reviewer_name: 'Sandra F',
      reviewer_avatar: null,
    },
    {
      id: 496096,
      title: null,
      comment:
        '\u003cp\u003eDavid was extremely informative.  We thoroughly enjoyed it! He made sure to point to the most popular works but took time to answer questions.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-06T00:00:00.000-05:00',
      reviewer_name: 'Thomas C',
      reviewer_avatar: null,
    },
    {
      id: 496095,
      title: null,
      comment:
        '\u003cp\u003eOur guide was great. He was very knowledgeable about the art and history of the Vatican. He spoke English well and we thought having the headsets to listen to him worked nicely. The Skip-The- Line was a must. The line to get regular tickets at the Vatican wrapped around the building. I would assume it would have taken hours without this tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-06T00:00:00.000-05:00',
      reviewer_name: 'Gaye R',
      reviewer_avatar: null,
    },
    {
      id: 496094,
      title: null,
      comment:
        '\u003cp\u003eThe whole trip was really well organised amidst crowds of people! Our guide Rosamba ? Was so knowledgeable she really highlighted the important art works and made our trip memorable!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-06T00:00:00.000-05:00',
      reviewer_name: 'Christine B',
      reviewer_avatar: null,
    },
    {
      id: 496103,
      title: null,
      comment:
        "\u003cp\u003eExcellent tour. Our guide Jorgia was very knowledgeable, enthusiastic and we really felt like she had been there when all the events she described took place. We've never had a guide that was as involved in the presentation as she was. Her descriptions and insight were amazing. Five stars really doesn't do her justice.\u003cbr/\u003e\nGreat tour!\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-01T00:00:00.000-05:00',
      reviewer_name: 'Ron T',
      reviewer_avatar: null,
    },
    {
      id: 496102,
      title: null,
      comment:
        '\u003cp\u003eThis tour is well worth doing, you really do skip the line and when you see the line you will be glad you did. Maria Theresa was a fabulous guide and ensured we saw everything in the 3 hours.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-01T00:00:00.000-05:00',
      reviewer_name: 'Janice W',
      reviewer_avatar: null,
    },
    {
      id: 496101,
      title: null,
      comment:
        '\u003cp\u003eLoved it - very informative. Guide was knowledgeable and easy to understand. Well organised. Would recommend\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-01T00:00:00.000-05:00',
      reviewer_name: 'Bradley L',
      reviewer_avatar: null,
    },
    {
      id: 496100,
      title: null,
      comment:
        '\u003cp\u003eThis tour was really amazing. Our guide, Fran, was excellent;  very knowledgeable, enthusiastic and professional. Thank you for making our visit so memorable.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-01T00:00:00.000-05:00',
      reviewer_name: 'Christine M',
      reviewer_avatar: null,
    },
    {
      id: 496099,
      title: null,
      comment:
        '\u003cp\u003eAbsolutely amazing tour! Yes you pay extra for skipping the line but it’s so worth it. Instead of staying for hours in the line we spent all that  valuable time exploring magnificent beauty of Vatican City. Our guide Francesca from City Wanders was very knowledgable and  professional , she made our experience even more enjoyable\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-05-01T00:00:00.000-05:00',
      reviewer_name: 'Alla B',
      reviewer_avatar: null,
    },
    {
      id: 496105,
      title: null,
      comment:
        '\u003cp\u003eSo happy we did faster than skip the line tour.  It was fantastic. Our guide was very knowledgeable, easy to understand and fun.  Meeting place was easy to find.  Tour was as advertised and I would highly recommended!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-29T00:00:00.000-05:00',
      reviewer_name: 'Arthur K',
      reviewer_avatar: null,
    },
    {
      id: 496104,
      title: null,
      comment:
        '\u003cp\u003eGreat tour, Manuela, kept us moving and engaged. She was a great tour guide with so much knowledge and details, it was crazy to hear all the history. The entire tour was so crowded with people but she kept us together and gave us tons of great information. Skip the line to get in, totally worth it, but inside, crowds often overwhelmed.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-29T00:00:00.000-05:00',
      reviewer_name: 'jill',
      reviewer_avatar: null,
    },
    {
      id: 409198,
      title: null,
      comment:
        '\u003cp\u003eRosie was our guide and she was very knowledgeable and her narration was very interesting. Vatican museums can be overwhelming but Rosie got us to see the important and the interesting things. With long queues, skip the line option was most useful- This is the best way to see the Vatican museums and the Sistine chapel.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-09T00:00:00.000-05:00',
      reviewer_name: 'Chandimani U',
      reviewer_avatar: null,
    },
    {
      id: 409197,
      title: null,
      comment:
        '\u003cp\u003eA well run tour thank you some interference with the headsets my only comment otherwise very good.\u003cbr/\u003e\nThe tour guide was excellent\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-09T00:00:00.000-05:00',
      reviewer_name: 'marcus',
      reviewer_avatar: null,
    },
    {
      id: 409199,
      title: null,
      comment:
        '\u003cp\u003eThis is well worth the extra money. You get to see the highlights with an extremely knowledgeable guide, Ella.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-08T00:00:00.000-05:00',
      reviewer_name: 'Caroline S',
      reviewer_avatar: null,
    },
    {
      id: 409200,
      title: null,
      comment:
        "\u003cp\u003eexcellent tour guide, very informative, disappointed that we couldn't get to st peters bascillica due to pope saying mass there,\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-03T00:00:00.000-05:00',
      reviewer_name: 'Helen B',
      reviewer_avatar: null,
    },
    {
      id: 409202,
      title: null,
      comment:
        '\u003cp\u003eExcellent  tour with a super guide (Agatha) who really made the tour come alive.\u003cbr/\u003e\nI would strongly recommend taking this guided tour to get the best of a memorable day and definitely faster / skip the line tickets to avoid the ques.\u003cbr/\u003e\nWell organised and run tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-02T00:00:00.000-05:00',
      reviewer_name: 'Kevin W',
      reviewer_avatar: null,
    },
    {
      id: 409201,
      title: null,
      comment:
        '\u003cp\u003eOur tour guide, I think his name was Mossima.  He was the best!  So entertaining and very knowledgeable about everything on this tour.  He knew how to keep our attention.  Loved the tour.  The right tour guide always make a huge difference.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-02T00:00:00.000-05:00',
      reviewer_name: 'CHERYL B',
      reviewer_avatar: null,
    },
    {
      id: 409205,
      title: null,
      comment:
        '\u003cp\u003eHad a really informative morning with an excellent guide who took us round the three sites . I believe her name was Luicci. Thank you\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-01T00:00:00.000-05:00',
      reviewer_name: 'Philip B',
      reviewer_avatar: null,
    },
    {
      id: 409204,
      title: null,
      comment:
        '\u003cp\u003eSuperb tour made completely enjoyable by our knowledgeable guide. \u003cbr/\u003e\nWe had Francesca - ask for her - she’s brilliant!!!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-01T00:00:00.000-05:00',
      reviewer_name: 'Jackie M',
      reviewer_avatar: null,
    },
    {
      id: 409203,
      title: null,
      comment:
        '\u003cp\u003eJulia was our guide, and she was excellent! We learned so much, and everything went smoothly. I highly recommend!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-04-01T00:00:00.000-05:00',
      reviewer_name: 'libbydemarco1',
      reviewer_avatar: null,
    },
    {
      id: 409208,
      title: null,
      comment:
        '\u003cp\u003eThis was such a great experience. We learned so much from our guide Alexsandra! She was extremely kind and helpfull if we had any questions. We were really impressed by her knowlegde and by the Vatican itself. I would recommend this tour and citywonders as a company. Very professional and well organised!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-29T00:00:00.000-05:00',
      reviewer_name: 'Sherene E',
      reviewer_avatar: null,
    },
    {
      id: 409207,
      title: null,
      comment:
        '\u003cp\u003eThe guide on the Tour was excellent. Very knowledgeable and very polite. She was an art graduate and was able to tell so much more about the paintings and the artists. The tour was long but not boring so that was a blessing. The skip the line ticket is well worth it as we sailed through security and wasted no time to enter the Vatican. City Wonders did a fab good would recommend them very professional.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-29T00:00:00.000-05:00',
      reviewer_name: 'Denise B',
      reviewer_avatar: null,
    },
    {
      id: 409206,
      title: null,
      comment:
        "\u003cp\u003eThe tour lasted about 3  and  a half hours, so the first thing I would say is take a drink/snack with you, you can get a little hot and dry. We went on a Monday (which apparently one of their busy days as the Vatican is closed to the public on a Sunday for obvious reasons), it was very busy and some of the rooms were tightly packed, so we had to wait until it had cleared a little before our guide could tell us about the room/paintings/tapestries etc. This being said it is a fantastic tour and we learned so much from our fabulous guide Flaminia. There was nothing she didn't know and was very patient with the crowds  and  us as a group. The Vatican is vast, the Sistine Chapel mesmerising, but St Peter's Basilica was the icing on the cake, just beautiful on a huge scale! We decided to pay the 10 euros extra and climb the Basilica dome ... it is hard work  and  can get quite narrow in places, but is well worth the climb; the views across the Vatican  and  Rome are breathtaking. \u003cbr/\u003e\nFlaminia stayed with us until the Basilica where we were left to spend as much time there as we wanted. She was a tour guide with an incredible university educated knowledge  and  it was clear she loves what she does, which showed in her presentation skills - thank you Flaminia. We booked through Viator ( and  City Tours) which to be honest, we do in every country we visit and we have never had a bad trip! Yes,  we would recommend Viator  and  if you love your history, this is the tour to purchase! :-)\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-29T00:00:00.000-05:00',
      reviewer_name: 'Howard K',
      reviewer_avatar: null,
    },
    {
      id: 409211,
      title: null,
      comment:
        '\u003cp\u003eWe had a great time.  Paula was amazing.  She was very knowledgable and friendly.  Everyone was at the tour early, so we got an early start.  All the museum was amazing, but personally I was most surprised to see the Dali paintings.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-27T00:00:00.000-05:00',
      reviewer_name: 'taleren_bloodsong',
      reviewer_avatar: null,
    },
    {
      id: 409210,
      title: null,
      comment:
        '\u003cp\u003eAmil was the best tour guide ever! She answered all questions and her art degree background helped with tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-27T00:00:00.000-05:00',
      reviewer_name: 'jkwarthomas',
      reviewer_avatar: null,
    },
    {
      id: 409209,
      title: null,
      comment:
        '\u003cp\u003eThis is one of those items it was well worth it to pay for a private tour.  While it was busy and crowded, our guide helped us have a great experience.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-27T00:00:00.000-05:00',
      reviewer_name: 'James D',
      reviewer_avatar: null,
    },
    {
      id: 409216,
      title: null,
      comment:
        '\u003cp\u003eFranco was fantastic. A mine of information. We loved our tour it was so informative and engaging and also a little bit fun\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-25T00:00:00.000-05:00',
      reviewer_name: 'Rachel L',
      reviewer_avatar:
        'http://cache-graphicslib.viator.com/graphicslib/media/11/rachel-l-account_45701649-45sq.jpg',
    },
    {
      id: 409215,
      title: null,
      comment:
        '\u003cp\u003eExcellent guided tour! Well worth the money and our guide (Lorena) was absolutely fantastic. Really knew her stuff and was super passionate and animated from start to finish\u003cbr/\u003e\nThe place itself was stunning. An absolute must for anyone visiting the city.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-25T00:00:00.000-05:00',
      reviewer_name: 'philiptmartin',
      reviewer_avatar: null,
    },
    {
      id: 409214,
      title: null,
      comment:
        '\u003cp\u003eWe enjoyed the professional information that Marco provided,  He must be one of your top guides!!!  The tour was such a great and holy experience!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-25T00:00:00.000-05:00',
      reviewer_name: 'Sherry F',
      reviewer_avatar: null,
    },
    {
      id: 409213,
      title: null,
      comment:
        '\u003cp\u003eGreat tour which was well organised and saved so much time. The explanation of the main features of the Sistine Chapel made the time spent there much more worthwhile. Our guide was very knowledgeable.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-25T00:00:00.000-05:00',
      reviewer_name: 'Melanie N',
      reviewer_avatar: null,
    },
    {
      id: 409212,
      title: null,
      comment:
        '\u003cp\u003eOur tour guide was Margarite. She was knowledgeable.  She kept track of our group, keeping us together.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-25T00:00:00.000-05:00',
      reviewer_name: 'Louise M',
      reviewer_avatar: null,
    },
    {
      id: 409218,
      title: null,
      comment:
        '\u003cp\u003eOur guide was very knowledgeable and the ticket reserving our time at the Vatican was necessary for avoiding a 2 to 3 hour line. Our guide did an excellent job keeping a good pace with the group while also pointing out all the important details from the museum to the Basilica. I thoroughly enjoyed every tour I took with City Wonders while in Italy.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-22T00:00:00.000-05:00',
      reviewer_name: 'e_beth',
      reviewer_avatar: null,
    },
    {
      id: 409217,
      title: null,
      comment:
        '\u003cp\u003eA really knowledgeable and engaging guide made this an especuallg interesting experuence. Amazing art and incredible buildings.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-22T00:00:00.000-05:00',
      reviewer_name: 'Neville C',
      reviewer_avatar: null,
    },
    {
      id: 409220,
      title: null,
      comment:
        '\u003cp\u003eThe tour guide was very knowledgeable and very interactive. The Faster than skip the line is worth the additional cost.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-21T00:00:00.000-05:00',
      reviewer_name: 'Matthew A',
      reviewer_avatar: null,
    },
    {
      id: 409219,
      title: null,
      comment:
        '\u003cp\u003eIt was a life long dream to visit the Sistine Chapel... Lived up to every expectation!  I cried!   Thank you Viator for getting me there.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-21T00:00:00.000-05:00',
      reviewer_name: 'kathriona d',
      reviewer_avatar: null,
    },
    {
      id: 406450,
      title: null,
      comment:
        '\u003cp\u003eA brilliant experience. Our guide, Asunta, was very knowledgeable and gave meaning and understanding to everything we saw. Surprisingly we had plenty of time to take in the magnificence of the Sistine chapel - we had expected to be rushed through.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-13T00:00:00.000-05:00',
      reviewer_name: 'Heather O',
      reviewer_avatar: null,
    },
    {
      id: 406452,
      title: null,
      comment:
        '\u003cp\u003eI had always wanted to visit the catacombs and am so glad that this unusual tour was available ! Louise was informative and passionate and kept us interested for 3 hours. It was great to visit more out-of-the way locations by coach, and I thought it was brilliant that the guides provided continuous information and stories between locations. Would recommend this tour to anyone\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-12T00:00:00.000-05:00',
      reviewer_name: 'Elyse K',
      reviewer_avatar: null,
    },
    {
      id: 406451,
      title: null,
      comment:
        '\u003cp\u003eTour was on time, well organised, informative and fun - "Manuella " our guide was exceptional, personalising the tour with her welcoming personality - she really made to tour a fun and meaningful experience - good value for money.  We attended during Cultural week so it was very busy as lots of monuments were free entry - she managed to negotiate us very smoothly through the crowds.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-12T00:00:00.000-05:00',
      reviewer_name: 'Carol L',
      reviewer_avatar: null,
    },
    {
      id: 406456,
      title: null,
      comment:
        '\u003cp\u003eThe organisation was very good, the rep Vasco was excellent, knowledgeable and very thoughtful, comfort breaks and times to view many treasures ( let’s not get into where they came from!)). It was well worth the money because of Vasco and the definite need to skip the Vatican queues.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-11T00:00:00.000-05:00',
      reviewer_name: 'Philip P',
      reviewer_avatar: null,
    },
    {
      id: 406455,
      title: null,
      comment:
        '\u003cp\u003eMy family of 4 , 2 adults and 2 college students really enjoyed this experience. Maria Teresa was a great tour guide who spoke English very well. She was able to explain all of the art and history behind the statues, paintings, and tapestries in the Vatican Museum, Church, and Sistine Chapel. To do this on our own would not have been anything like this. We would have had no idea what we were looking at, and would have waited in line forever to get in!!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-11T00:00:00.000-05:00',
      reviewer_name: 'Lillian M',
      reviewer_avatar: null,
    },
    {
      id: 406454,
      title: null,
      comment:
        "\u003cp\u003eWent on the tour on a busy Friday afternoon,  our tour guide Laura Sensi whisked us through the queues and into the Vatican in no time hassle free.  Laura's talk through all the interesting features of the Sistine chapel was amazing.  Her insight into everything within the Vatican museum was fantastic and all done without referring to notes or books. Her humour and friendliness definitely made this fab experience even better.  Can't recommend her highly enough.\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-11T00:00:00.000-05:00',
      reviewer_name: 'Jonathan W',
      reviewer_avatar: null,
    },
    {
      id: 406453,
      title: null,
      comment:
        '\u003cp\u003eEdwardo was just great.we felt very comfortable and taken care of. His sense of humor  had us smiling.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-11T00:00:00.000-05:00',
      reviewer_name: 'debra m',
      reviewer_avatar: null,
    },
    {
      id: 406457,
      title: null,
      comment:
        '\u003cp\u003eOur guide Edy was superb.  Very informative.  Very knowledgeable on the history of the Vatican . Would highly recommend this tour.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-08T00:00:00.000-06:00',
      reviewer_name: 'sharon l',
      reviewer_avatar: null,
    },
    {
      id: 406460,
      title: null,
      comment:
        '\u003cp\u003eWas really a good and informative tour that covered almost everything. And the best part was it actually skips the line, there is a different line when entering the tour which is almost instantaneous entry.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-07T00:00:00.000-06:00',
      reviewer_name: 'rafie.omar23',
      reviewer_avatar: null,
    },
    {
      id: 406459,
      title: null,
      comment:
        '\u003cp\u003eVal (Tuesday 5th March) was great loved every minute would recommend to anyone. Only disappointment was gift shop shut at 5 and we missed it.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-07T00:00:00.000-06:00',
      reviewer_name: 'Stuart T',
      reviewer_avatar: null,
    },
    {
      id: 406458,
      title: null,
      comment:
        '\u003cp\u003eFrancesca was very knowledgeable has good command of English  and very helpful. I more interested to reserch more about the Vatican and its history.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-07T00:00:00.000-06:00',
      reviewer_name: 'Martin M',
      reviewer_avatar: null,
    },
    {
      id: 406462,
      title: null,
      comment:
        '\u003cp\u003ei cannot say enough nice words about our guide and the tour.  She was extremely knowledgable, thoughtful, relational, and professional.    We learned much history, and had a marvelous time!  Thank you!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-06T00:00:00.000-06:00',
      reviewer_name: 'Joy G',
      reviewer_avatar: null,
    },
    {
      id: 406461,
      title: null,
      comment:
        '\u003cp\u003eEasy to find the meet up spot outside the Vatican, lots of people there to point you in the right direction. Got in so quick  and  easy skipping the line was amazing! Once inside our guide was so knowledgeable  and  clearly passionate about all of the artwork/history he was talking about. Really great experience overall!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-06T00:00:00.000-06:00',
      reviewer_name: 'Julie S',
      reviewer_avatar: null,
    },
    {
      id: 406464,
      title: null,
      comment:
        '\u003cp\u003eJulianna was incredible! and extremely knowledgeable. She was such a great guide! Definitely wear good shoes\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-04T00:00:00.000-06:00',
      reviewer_name: 'PAMELA W',
      reviewer_avatar: null,
    },
    {
      id: 406463,
      title: null,
      comment:
        "\u003cp\u003eWe have just come back from are trip to Rome today...There were 8 of us in the trip altogether. ...This trip is worth booking as you skip the line and there is 30, 000 people going to see the Vatican every day so it's worth every penny. ..The tour guild Sabrina was lovely and very knowledgeable about the tour, a think it's better going with a guild as they can point out things you would never know about if you was on your own....If you don't book anything else book this tour, everything went really smothley. ..And booking through VIATOR is always a pleasure\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-03-04T00:00:00.000-06:00',
      reviewer_name: 'cooke_joanne',
      reviewer_avatar: null,
    },
    {
      id: 354217,
      title: null,
      comment:
        '\u003cp\u003eOur tour guide Christian was excellent, very knowledgeable  and  enthusiastic. Without him I don’t think the tour would have been the same.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-02-28T00:00:00.000-06:00',
      reviewer_name: 'Sandra M',
      reviewer_avatar: null,
    },
    {
      id: 354220,
      title: null,
      comment:
        '\u003cp\u003eOur tour guide, Azule was very informative, fluent in English and has a great passion for art and art history.  There are many stairs on the Vatican Museum tour and considerable amount of walking.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-02-27T00:00:00.000-06:00',
      reviewer_name: 'Marcie S',
      reviewer_avatar: null,
    },
    {
      id: 354219,
      title: null,
      comment:
        "\u003cp\u003eA must spiritual destination for every christian ,well managed and a 5 stars Eduardo guide.\u003cbr/\u003e\nWhere Genius's Arts meet Faith\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-02-27T00:00:00.000-06:00',
      reviewer_name: 'Mario K',
      reviewer_avatar: null,
    },
    {
      id: 354218,
      title: null,
      comment:
        '\u003cp\u003eChristian is a very knowledgable guide, passionate about the art and keen to share his insights. The Vatican is a sight to behold.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-02-27T00:00:00.000-06:00',
      reviewer_name: 'Alison M',
      reviewer_avatar: null,
    },
    {
      id: 354221,
      title: null,
      comment:
        '\u003cp\u003eMy daughter and I took the Vatican tour with the lovely Lucia. This was not our first time in the Vatican museum, but we learnt many new facts thanks to Lucia.s vast knowledge of history and art. Skipping the line was a great bonus, and Lucia guided us really well about getting along in this vast museum and about the art and history of the place. We loved the tour!!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-02-26T00:00:00.000-06:00',
      reviewer_name: 'Taly C',
      reviewer_avatar: null,
    },
    {
      id: 354225,
      title: null,
      comment:
        '\u003cp\u003eAbsolute must with the number of visitors even in February which I thought was off season. Our guide Maria Roschita was very informative  and  knowledgeable about the subject. She guided us through the masses of people without missing out any of the major items. Day well spent according to my 25 daughter also!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-02-25T00:00:00.000-06:00',
      reviewer_name: 'Jacob T',
      reviewer_avatar: null,
    },
    {
      id: 354224,
      title: null,
      comment:
        '\u003cp\u003eAn excellent tour with Lucia as a most knowledgable guide. The queue would have been a 3 hour wait - so the cost was definitely worth while!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-02-25T00:00:00.000-06:00',
      reviewer_name: 'Caroline S',
      reviewer_avatar: null,
    },
    {
      id: 354223,
      title: null,
      comment:
        '\u003cp\u003eLaura was great  and made the experience truly wonderful. She had amazing knowledge and could answer all my questions.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-02-25T00:00:00.000-06:00',
      reviewer_name: 'Paul S',
      reviewer_avatar: null,
    },
    {
      id: 354222,
      title: null,
      comment:
        '\u003cp\u003eChristina from City Wonder Tours was amazing. She was friendly and professional and took the time to even learn our names.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-02-25T00:00:00.000-06:00',
      reviewer_name: 'Dominique F',
      reviewer_avatar:
        'http://cache-graphicslib.viator.com/graphicslib/media/76/dominique-f-account_24626038-45sq.jpg',
    },
    {
      id: 354226,
      title: null,
      comment:
        '\u003cp\u003eFrom start to finish, absolute first class. Apart from a couple of late shows, which slightly delayed the tour (being picky, but 5 minutes), the 3 hour was a great experience. The instructions for the meeting point was clear. Our tour guide was polite, friendly and very knowledgeable. The Vatican was mind blowing. I thought the 3 hours might have been too much, but it flew by with so much to see. Highly recommended.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-01-29T00:00:00.000-06:00',
      reviewer_name: 'Ian S',
      reviewer_avatar: null,
    },
    {
      id: 354228,
      title: null,
      comment:
        '\u003cp\u003eWe choose this option for our trip to Rome. We do not regret it at all. We were able to skip any lines that existed. Laura was awesome!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-01-28T00:00:00.000-06:00',
      reviewer_name: 'Gerald B',
      reviewer_avatar: null,
    },
    {
      id: 354227,
      title: null,
      comment:
        '\u003cp\u003eOur tour guide, Salvatore was excellent.  Very knowledgeable and thorough.  Salvatore made the tour well worth it!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-01-28T00:00:00.000-06:00',
      reviewer_name: 'Christine',
      reviewer_avatar: null,
    },
    {
      id: 354229,
      title: null,
      comment:
        '\u003cp\u003eVery easy meeting place, excellent tour.  Guide was outstanding.  Got exactly what we expected.  The Vatican was very crowded the day we went.  Using this tour was extremely beneficial, as the lines for entry were two-three hours long.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-01-22T00:00:00.000-06:00',
      reviewer_name: 'eppyvox',
      reviewer_avatar: null,
    },
    {
      id: 354230,
      title: null,
      comment:
        '\u003cp\u003eThe tour guide we had was awesome, she was so knowledgeable and articulate with her words.  We all enjoyed her skilled knowledge!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-01-21T00:00:00.000-06:00',
      reviewer_name: 'Caryn A',
      reviewer_avatar: null,
    },
    {
      id: 354231,
      title: null,
      comment:
        "\u003cp\u003eAs one of the must see attractions of Rome this tour is one you can't miss! The tour guide was knowledgeable and friendly. The Vatican museum, Sistine Chapel, and St. Peter's Basilica were awe inspiring! My husband and I loved the tour and strongly recommend it to anyone visiting Rome.\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-01-15T00:00:00.000-06:00',
      reviewer_name: 'Kristine K',
      reviewer_avatar:
        'http://cache-graphicslib.viator.com/graphicslib/media/62/kristine-k-account_26200162-45sq.jpg',
    },
    {
      id: 354233,
      title: null,
      comment:
        '\u003cp\u003eThis was a great tour. Well organized and totally flawless logistically. Tour guide Krista was so knowledgeable and well organized. I had a great time and saw everything I wanted to see. You really do skip a number of lines and save a lot of time/headache. This is the way to go!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-01-14T00:00:00.000-06:00',
      reviewer_name: 'Dan C',
      reviewer_avatar: null,
    },
    {
      id: 354232,
      title: null,
      comment:
        '\u003cp\u003eOur guide was great, spoke very good English and had no problems answering questions from people in the group. Our guide was very informative about each section of the tour but did not stall or tKe too much time in one spot. My wife and I both very much enjoyed our tour of the Vatican, Sisteen Chapel and St. Peter’s bacilaica. I would highly recommend this tour to anyone going to Rome.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2019-01-14T00:00:00.000-06:00',
      reviewer_name: 'Richard S',
      reviewer_avatar: null,
    },
    {
      id: 354234,
      title: null,
      comment:
        '\u003cp\u003eThis tour was fantastic. Our Guide Sara was absolutely great at her job. A gold mine of information which she made interesting  and  fun. Questions were answered well, she seems to be more than expert! She really made sure we enjoyed the whole experience.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2018-12-31T00:00:00.000-06:00',
      reviewer_name: 'merril.neill',
      reviewer_avatar:
        'http://cache-graphicslib.viator.com/graphicslib/media/2c/merril-neill-account_32010284-45sq.jpg',
    },
    {
      id: 354235,
      title: null,
      comment:
        '\u003cp\u003eExcellent tour and guide.  Very knowledgeable and thorough.  My second time to the Vatican and it was impressive as the first visit.  A must-see when in Rome!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2018-12-24T00:00:00.000-06:00',
      reviewer_name: 'Garrett H',
      reviewer_avatar: null,
    },
    {
      id: 354237,
      title: null,
      comment:
        '\u003cp\u003eThe guide Giusepe was amazing. He explained everything very well and carefully so anyone could understand. At the end of the visit he told us what we should do before leaving Vatican City. The organization of city wonders people was very good.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2018-12-19T00:00:00.000-06:00',
      reviewer_name: 'Nica75',
      reviewer_avatar: null,
    },
    {
      id: 354236,
      title: null,
      comment:
        '\u003cp\u003eJulia is one of the best tour guides in all of vatican City.She was informative, constructive and super intelligent.\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2018-12-19T00:00:00.000-06:00',
      reviewer_name: 'Yakir T',
      reviewer_avatar: null,
    },
    {
      id: 354238,
      title: null,
      comment:
        "\u003cp\u003eWe definitely had a great time touring the Vatican, Sistine Chapel, and St Peter's Basilica because of Umbra. She made the tour fun and entertaining with her stories and knowledge, and the 'inside stories'. Definitely worth it!\u003c/p\u003e",
      rating: '5.0',
      user_id: null,
      reviewed_at: '2018-12-17T00:00:00.000-06:00',
      reviewer_name: 'ddescueta',
      reviewer_avatar: null,
    },
    {
      id: 354239,
      title: null,
      comment:
        '\u003cp\u003eFantastic!!What an amazing tour!! Stephanie was an amazingly knowledgeable and passionate tour! Well worth it and enjoyed by our whole party of eight which spanned three generations!! Thank you\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2018-12-14T00:00:00.000-06:00',
      reviewer_name: 'Maria K',
      reviewer_avatar: null,
    },
    {
      id: 354240,
      title: null,
      comment:
        '\u003cp\u003eGreat tour!!!skip the line and meet point with great instructions on the ticket alessandro was a great tour guide with knowledge and fun it’s worth it in my eyes thank you you guys for welcoming us to Rome!!!\u003c/p\u003e',
      rating: '5.0',
      user_id: null,
      reviewed_at: '2018-12-03T00:00:00.000-06:00',
      reviewer_name: 'octavio t',
      reviewer_avatar: null,
    },
  ],
};

export default mockTour;
